DoF: 3
max_episode_steps: 20
param_keys: []
xml_path: environments/franka/assets/kitchen_franka/kitchen_assets/franka_free.xml
init_pos_noise: 0.
task_reward: true
reward: reach
goal: [0.5, -0.35, 0.1]
